[Draft]: Upload example captures from web interface
RolnickLab/ami-platform pull request #281
Opened 2023-10-13 15:04 UTC by annavik

In this PR we make it possible to add and remove example captures from deployments. It's possible to upload 
one or many at a time.

**Left to do:**
- Some more client side check (for example restrict the file size before we call BE)
- Do we have a max number of example captures allowed for a deployment? I could make a client side check here as well.
- Small UI tweaks
  - Update "Choose images" card (plus button instead of text button)
  - Reverse the capture order so that latest uploaded shows up last (?)

**Screenshot (last card shows upload in progress):**

<img width="611" alt="Screenshot 2023-10-13 at 16 58 04" src="https://github.com/RolnickLab/ami-platform/assets/11680517/678eaf7c-7169-4c0a-8540-668258e0cdc9">

2023-10-16 04:00 UTC, mihow commented
I love how the errors are handled from backend validation! Thank you
<img width="775" alt="image" src="https://github.com/RolnickLab/ami-platform/assets/158175/ceba7f3d-bb09-4ba8-8ef1-6ae9175c3daa">

2023-10-16 04:47 UTC, mihow requested changes
Works great! One small request left in my comments. Then also one lager design decision we need to make related to the delete behavior. Currently deleting the example images will have no effect on the created source images after they are uploaded. See https://github.com/RolnickLab/ami-platform/pull/274#issuecomment-1763718715

2023-10-16 04:47 UTC, mihow commented on ui/src/pages/deployment-details/deployment-details-form/section-source-images/section-source-images.tsx
> -                label={translate(STRING.FIELD_LABEL_EXAMPLE_CAPTURES)}
I'm thinking we should remove this count. The "Example captures" become regular captures after you upload them and I don't think we should expose info about this proxy model.

<img width="606" alt="image" src="https://github.com/RolnickLab/ami-platform/assets/158175/5ded5bf9-71c5-484e-9cf9-deb4257cd110">

2023-10-16 12:09 UTC, annavik commented
PR is updated with some tweaks tweaks!

Some remaining questions:
- Should we restrict file size client side?
- Should we restrict max number of images client side?
- On upload/delete error, we want to show error info and make it possible to retry. Which button option do you prefer? In both cases we show the error info on hover and trigger retry on click.
<img width="220" alt="Screenshot 2023-10-16 at 13 52 50" src="https://github.com/RolnickLab/ami-platform/assets/11680517/43b47585-1175-42c0-a567-76edb9146faa">
<br/>
<img width="203" alt="Screenshot 2023-10-16 at 13 54 13" src="https://github.com/RolnickLab/ami-platform/assets/11680517/56ae9fb1-4c12-4663-9c34-93ca0b94b67d">

2023-10-17 03:23 UTC, mihow commented
> PR is updated with some tweaks tweaks!
> 
> Some remaining questions:
> 
> * Should we restrict file size client side?
> * Should we restrict max number of images client side?
> * On upload/delete error, we want to show error info and make it possible to retry. Which button option do you prefer? In both cases we show the error info on hover and trigger retry on click.
> 
> <img alt="Screenshot 2023-10-16 at 13 52 50" width="220" src="https://user-images.githubusercontent.com/11680517/275497279-43b47585-1175-42c0-a567-76edb9146faa.png">
> <img alt="Screenshot 2023-10-16 at 13 54 13" width="203" src="https://user-images.githubusercontent.com/11680517/275497283-56ae9fb1-4c12-4663-9c34-93ca0b94b67d.png">

- You can use the same maximum file size constant as for the user icon and project image. I increased it to 10MB! We will have auto thumbnailing eventually... 
- Let's set the limit based on when the UI starts to break down. 20? Then provide a message saying "To upload more than N images you must configure a data source. See Help."
- For the Retry method. I like seeing "Retry" in a button. But I kind of like button in white. What about a red warning triangle on a white button that just says Retry?
- Will you make the data source field not-required?

2023-10-17 04:16 UTC, mihow commented
Oh new issue! The Deployment needs to exist before the Example Capture is saved. Can we hide or disable the image upload section and say "Save deployment before uploading images"?

2023-10-17 04:45 UTC, mihow commented
I don't know how to recreate this one, but it happened once where I uploaded 2 successfully, then the 3rd failed, but all of them showed the Retry button!
<img width="742" alt="image" src="https://github.com/RolnickLab/ami-platform/assets/158175/ab2f4018-ab02-40b4-92b9-b16eb19a7b73">

2023-10-17 05:55 UTC, mihow commented
@annavik 

> From a user perspective, if images are about to be permanently deleted perhaps we should use the trash icon instead of the cross. Also introduce a confirm step?

I think yes! Let's rename to "Test captures" and use the trash icon with a confirm. The backend is now deleting the uploaded capture if the source image is deleted and vice versa. 

The "Test captures" collection could also be used when creating a job (Select the "Test captures" collection to test models on this hand-picked subset)

2023-10-17 14:46 UTC, annavik commented
> I don't know how to recreate this one, but it happened once where I uploaded 2 successfully, then the 3rd failed, but all of them showed the Retry button! <img alt="image" width="742" src="https://user-images.githubusercontent.com/158175/275711670-ab2f4018-ab02-40b4-92b9-b16eb19a7b73.png">

Good catch, thanks!! Will check it out

2023-10-18 04:53 UTC, mihow commented
Small design thought: Use a white button for the Retry buttons, but with the red warning triangle inside. I could go either way.

2023-10-19 06:39 UTC, mihow approved these changes

2023-10-19 06:41 UTC, merged