Show pipeline ID
RolnickLab/ami-platform pull request #479
Opened 2024-08-02 15:35 UTC by annavik

Fixes #475. Also including some other small tweaks for default sort order and dialog trigger apperance.

**Before:**
<img width="1179" alt="Skärmavbild 2024-08-02 kl  17 33 53" src="https://github.com/user-attachments/assets/520ef345-abc5-4c88-b850-877a2b92720d">

**After:**
<img width="1198" alt="Skärmavbild 2024-08-02 kl  17 31 29" src="https://github.com/user-attachments/assets/09b2eafc-a94b-4e42-9c14-be994cfcb53f">

2024-08-02 22:35 UTC, mihow requested changes
Thank you! Will you make the column sortable too?

2024-08-04 20:40 UTC, annavik commented
> Thank you! Will you make the column sortable too?

I actually tried, but it seemed to have no effect on the fetch call. Perhaps sorting by id supported by backend? Or I used the wrong key, I tried `id` and `_id` ...

2024-08-05 06:57 UTC, annavik commented
This seems to be updated, thanks! We can now sort by ID and I also made this the default sort order ✅

2024-08-05 16:44 UTC, mihow approved these changes
Thanks for noticing that I added the option in the other PR! I intended to mention that.

2024-08-05 16:45 UTC, merged